-- EJECUTA ESTO EN EL EDITOR SQL DE SUPABASE

-- 1. Tabla de Perfiles (Extensión de Supabase Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  account_number TEXT UNIQUE NOT NULL,
  balance DECIMAL DEFAULT 1000.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Tabla de Transacciones
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES profiles(id),
  receiver_id UUID REFERENCES profiles(id),
  amount DECIMAL NOT NULL,
  description TEXT,
  type TEXT CHECK (type IN ('TRANSFER', 'DEPOSIT', 'WITHDRAW')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Habilitar Row Level Security (RLS) - Opcional para pruebas
-- Por ahora deshabilitado para que la API pueda operar libremente
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
